### ISSUE TITLE
Exception when compiling

### ISSUE THREAD

**Issue by gcadien** [mirkosertic/Bytecoder#215]
I've just started experimenting with Bytecoder and have run into the following exception when trying to compile simple HelloWorld.

Linux jellikit 5.2.9-arch1-1-ARCH #1 SMP PREEMPT Fri Aug 16 11:29:43 UTC 2019 x86_64 GNU/Linux

openjdk version "12.0.2" 2019-07-16
OpenJDK Runtime Environment (build 12.0.2+10)
OpenJDK 64-Bit Server VM (build 12.0.2+10, mixed mode)

```java
import java.util.List;

public class HelloWorld {

  public static void main(String[] args) {
    var l = List.of("Hello", "World");
    l.stream().forEach(System.out::println);
  }
}
```
Exception in thread "main" java.lang.RuntimeException: Error linking class java.lang.Module
        at de.mirkosertic.bytecoder.core.BytecodeLinkerContext.resolveClass(BytecodeLinkerContext.java:111)
        at de.mirkosertic.bytecoder.core.BytecodeLinkedClass.link(BytecodeLinkedClass.java:256)
        at de.mirkosertic.bytecoder.core.BytecodeLinkedClass.resolveMethodSignatureAndBody(BytecodeLinkedClass.java:380)
        at de.mirkosertic.bytecoder.core.BytecodeLinkedClass.resolveStaticMethod(BytecodeLinkedClass.java:363)
        at de.mirkosertic.bytecoder.core.BytecodeInstructionINVOKESTATIC.performLinking(BytecodeInstructionINVOKESTATIC.java:34)
        at de.mirkosertic.bytecoder.core.BytecodeLinkedClass.resolveMethodSignatureAndBody(BytecodeLinkedClass.java:393)
        at de.mirkosertic.bytecoder.core.BytecodeLinkedClass.resolveStaticMethod(BytecodeLinkedClass.java:363)
        at de.mirkosertic.bytecoder.core.BytecodeInstructionINVOKESTATIC.performLinking(BytecodeInstructionINVOKESTATIC.java:34)
        at de.mirkosertic.bytecoder.core.BytecodeLinkedClass.resolveMethodSignatureAndBody(BytecodeLinkedClass.java:393)
        at de.mirkosertic.bytecoder.core.BytecodeLinkedClass.resolveStaticMethod(BytecodeLinkedClass.java:363)
        at de.mirkosertic.bytecoder.core.BytecodeInstructionINVOKESTATIC.performLinking(BytecodeInstructionINVOKESTATIC.java:34)
        at de.mirkosertic.bytecoder.core.BytecodeLinkedClass.resolveMethodSignatureAndBody(BytecodeLinkedClass.java:393)
        at de.mirkosertic.bytecoder.core.BytecodeLinkedClass.resolveVirtualMethod(BytecodeLinkedClass.java:283)
        at de.mirkosertic.bytecoder.core.BytecodeInstructionINVOKEINTERFACE.performLinking(BytecodeInstructionINVOKEINTERFACE.java:45)
        at de.mirkosertic.bytecoder.core.BytecodeLinkedClass.resolveMethodSignatureAndBody(BytecodeLinkedClass.java:393)
        at de.mirkosertic.bytecoder.core.BytecodeLinkedClass.resolveVirtualMethod(BytecodeLinkedClass.java:283)
        at de.mirkosertic.bytecoder.core.BytecodeLinkedClass.resolveVirtualMethod(BytecodeLinkedClass.java:290)
        at de.mirkosertic.bytecoder.core.BytecodeInstructionINVOKEVIRTUAL.performLinking(BytecodeInstructionINVOKEVIRTUAL.java:50)
        at de.mirkosertic.bytecoder.core.BytecodeLinkedClass.resolveMethodSignatureAndBody(BytecodeLinkedClass.java:393)
        at de.mirkosertic.bytecoder.core.BytecodeLinkedClass.resolvePrivateMethod(BytecodeLinkedClass.java:338)
        at de.mirkosertic.bytecoder.core.BytecodeInstructionINVOKESPECIAL.performLinking(BytecodeInstructionINVOKESPECIAL.java:40)
        at de.mirkosertic.bytecoder.core.BytecodeLinkedClass.resolveMethodSignatureAndBody(BytecodeLinkedClass.java:393)
        at de.mirkosertic.bytecoder.core.BytecodeLinkedClass.resolveVirtualMethod(BytecodeLinkedClass.java:283)
        at de.mirkosertic.bytecoder.core.BytecodeLinkedClass.resolveInheritedOverriddenMethods(BytecodeLinkedClass.java:450)
        at de.mirkosertic.bytecoder.core.BytecodeLinkerContext.resolveAbstractMethodsInSubclasses(BytecodeLinkerContext.java:138)
        at de.mirkosertic.bytecoder.backend.CompileTarget.compile(CompileTarget.java:94)
        at de.mirkosertic.bytecoder.cli.BytecoderCLI.main(BytecoderCLI.java:115)
Caused by: java.lang.RuntimeException: Error linking class java.lang.ModuleLayer
        at de.mirkosertic.bytecoder.core.BytecodeLinkerContext.resolveClass(BytecodeLinkerContext.java:111)
        at de.mirkosertic.bytecoder.core.BytecodeLinkerContext.resolveTypeRef(BytecodeLinkerContext.java:132)
        at de.mirkosertic.bytecoder.core.BytecodeLinkedClass.resolveInstanceField(BytecodeLinkedClass.java:205)
        at de.mirkosertic.bytecoder.core.BytecodeInstructionPUTFIELD.performLinking(BytecodeInstructionPUTFIELD.java:41)
        at de.mirkosertic.bytecoder.core.BytecodeLinkedClass.resolveMethodSignatureAndBody(BytecodeLinkedClass.java:393)
        at de.mirkosertic.bytecoder.core.BytecodeLinkedClass.resolveConstructorInvocation(BytecodeLinkedClass.java:313)
        at de.mirkosertic.bytecoder.core.BytecodeInstructionINVOKESPECIAL.performLinking(BytecodeInstructionINVOKESPECIAL.java:36)
        at de.mirkosertic.bytecoder.core.BytecodeLinkedClass.resolveMethodSignatureAndBody(BytecodeLinkedClass.java:393)
        at de.mirkosertic.bytecoder.core.BytecodeLinkedClass.resolveStaticMethod(BytecodeLinkedClass.java:363)
        at de.mirkosertic.bytecoder.core.BytecodeLinkedClass.resolveClassInitializer(BytecodeLinkedClass.java:141)
        at de.mirkosertic.bytecoder.core.BytecodeLinkerContext.resolveClass(BytecodeLinkerContext.java:98)
        ... 26 more
Caused by: java.lang.IllegalStateException: Cannot link static field bootLayer in java.lang.System
        at de.mirkosertic.bytecoder.core.BytecodeInstructionGETSTATIC.performLinking(BytecodeInstructionGETSTATIC.java:41)
        at de.mirkosertic.bytecoder.core.BytecodeLinkedClass.resolveMethodSignatureAndBody(BytecodeLinkedClass.java:393)
        at de.mirkosertic.bytecoder.core.BytecodeLinkedClass.resolveStaticMethod(BytecodeLinkedClass.java:363)
        at de.mirkosertic.bytecoder.core.BytecodeInstructionINVOKESTATIC.performLinking(BytecodeInstructionINVOKESTATIC.java:34)
        at de.mirkosertic.bytecoder.core.BytecodeLinkedClass.resolveMethodSignatureAndBody(BytecodeLinkedClass.java:393)
        at de.mirkosertic.bytecoder.core.BytecodeLinkedClass.resolveStaticMethod(BytecodeLinkedClass.java:363)
        at de.mirkosertic.bytecoder.core.BytecodeInstructionINVOKESTATIC.performLinking(BytecodeInstructionINVOKESTATIC.java:34)
        at de.mirkosertic.bytecoder.core.BytecodeLinkedClass.resolveMethodSignatureAndBody(BytecodeLinkedClass.java:393)
        at de.mirkosertic.bytecoder.core.BytecodeLinkedClass.resolveConstructorInvocation(BytecodeLinkedClass.java:313)
        at de.mirkosertic.bytecoder.core.BytecodeInstructionINVOKESPECIAL.performLinking(BytecodeInstructionINVOKESPECIAL.java:36)
        at de.mirkosertic.bytecoder.core.BytecodeLinkedClass.resolveMethodSignatureAndBody(BytecodeLinkedClass.java:393)
        at de.mirkosertic.bytecoder.core.BytecodeLinkedClass.resolveStaticMethod(BytecodeLinkedClass.java:363)
        at de.mirkosertic.bytecoder.core.BytecodeLinkedClass.resolveClassInitializer(BytecodeLinkedClass.java:141)
        at de.mirkosertic.bytecoder.core.BytecodeLinkerContext.resolveClass(BytecodeLinkerContext.java:98)

**Comment by mirkosertic** [comment]
Merged to master
