### ISSUE TITLE
Kotlin to WASM - by lazy init does not work

### ISSUE THREAD

**Issue by WhiteHexagon** [mirkosertic/Bytecoder#333]
Another Kotlin oddity, but I have managed to track the exception down to the following `by lazy`.  I am using the shadowJar, so I would have expected the Kotlin stdlib to be included, although this seems to be something reflection based from standard Java... 

Here is the command line I am using:

`java -jar bytecoder-cli-2019-06-13-executable.jar -classpath=./build/libs/art-trimmed-all.jar -mainclass=art.EntryKotlin -builddirectory=build -backend=wasm -minify=false -optimizationlevel=ALL -filenameprefix=main -maximumwasmpages=1024`

and the code that generates the exception below.

```
class EntryKotlin {
    val me: String by lazy {
        "Hola"
    }

    init {
        println("new entry kotlin")
        //val nada = Class.forName("")
        Main()
    }

    companion object {
        @JvmStatic
        fun main(args: Array<String>?) {
            EntryKotlin()
        }
    }
}
```

```
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: java.lang.RuntimeException: Error linking class art.EntryKotlin
        at de.mirkosertic.bytecoder.core.BytecodeLinkerContext.resolveClass(BytecodeLinkerContext.java:111)
        at de.mirkosertic.bytecoder.backend.CompileTarget.compile(CompileTarget.java:81)
        at de.mirkosertic.bytecoder.cli.BytecoderCLI.main(BytecoderCLI.java:111)
        ... 8 more
Caused by: java.lang.RuntimeException: Error linking class kotlin.jvm.internal.Reflection
        at de.mirkosertic.bytecoder.core.BytecodeLinkerContext.resolveClass(BytecodeLinkerContext.java:111)
        at de.mirkosertic.bytecoder.core.BytecodeInstructionINVOKESTATIC.performLinking(BytecodeInstructionINVOKESTATIC.java:33)
        at de.mirkosertic.bytecoder.core.BytecodeLinkedClass.resolveMethodSignatureAndBody(BytecodeLinkedClass.java:400)
        at de.mirkosertic.bytecoder.core.BytecodeLinkedClass.resolveStaticMethod(BytecodeLinkedClass.java:370)
        at de.mirkosertic.bytecoder.core.BytecodeLinkedClass.resolveClassInitializer(BytecodeLinkedClass.java:148)
        at de.mirkosertic.bytecoder.core.BytecodeLinkerContext.resolveClass(BytecodeLinkerContext.java:98)
        ... 10 more
Caused by: java.lang.IllegalStateException: Cannot find static method forName in java/lang/Class with signature java.lang.Class(java.lang.String)
        at de.mirkosertic.bytecoder.core.BytecodeInstructionINVOKESTATIC.performLinking(BytecodeInstructionINVOKESTATIC.java:35)
        at de.mirkosertic.bytecoder.core.BytecodeLinkedClass.resolveMethodSignatureAndBody(BytecodeLinkedClass.java:400)
        at de.mirkosertic.bytecoder.core.BytecodeLinkedClass.resolveStaticMethod(BytecodeLinkedClass.java:370)
        at de.mirkosertic.bytecoder.core.BytecodeLinkedClass.resolveClassInitializer(BytecodeLinkedClass.java:148)
        at de.mirkosertic.bytecoder.core.BytecodeLinkerContext.resolveClass(BytecodeLinkerContext.java:98)
        ... 15 more

```

**Comment by mirkosertic** [comment]
It seems you are using an outdated Bytecoder release.

Please take a look at the Bytecoder manual located here: https://mirkosertic.github.io/Bytecoder/chapter-1/page-1-d/

The Class.forName() Reflection API is only supported in the latest Bytecoder release. Please upgrade your Dependencies and *also* the JavaScript Bootstrap code according the manual and the provided examples. Then your testcase should work.

**Comment by WhiteHexagon** [comment]
I tried 2019-12-08 and also just now the 2020-02-29 and still getting an error using 'by lazy' in Kotlin:
```

INFO: Linked  java.lang.StringBuilder
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)
Caused by: java.lang.RuntimeException: Error linking class sun.nio.cs.UTF_8
        at de.mirkosertic.bytecoder.core.BytecodeLinkerContext.resolveClass(BytecodeLinkerContext.java:121)
        at de.mirkosertic.bytecoder.backend.CompileTarget.compile(CompileTarget.java:97)
        at de.mirkosertic.bytecoder.cli.BytecoderCLI.main(BytecoderCLI.java:124)
        ... 8 more
Caused by: java.lang.IllegalStateException: Cannot find constructor <init> in java/lang/AbstractStringBuilder with signature VOID(INT) in class java.lang.AbstractStringBuilder
        at de.mirkosertic.bytecoder.core.BytecodeInstructionINVOKESPECIAL.performLinking(BytecodeInstructionINVOKESPECIAL.java:37)
        at de.mirkosertic.bytecoder.core.BytecodeLinkedClass.resolveMethodSignatureAndBody(BytecodeLinkedClass.java:412)
        at de.mirkosertic.bytecoder.core.BytecodeLinkedClass.resolveConstructorInvocation(BytecodeLinkedClass.java:332)
        at de.mirkosertic.bytecoder.core.BytecodeInstructionINVOKESPECIAL.performLinking(BytecodeInstructionINVOKESPECIAL.java:36)
        at de.mirkosertic.bytecoder.core.BytecodeLinkedClass.resolveMethodSignatureAndBody(BytecodeLinkedClass.java:412)

```

**Comment by WhiteHexagon** [comment]
Also you mention the bootstrap code.  Is the new approach optional? it seems like quite a bit more js, and I was trying to avoid any at all :)  Is it possible to configure bytecoder from within my Kotlin, and the cli tool generates any extra glue?  especially all the garbage collector stuff?

**Comment by WhiteHexagon** [comment]
I removed my use of 'by lazy' and replaced it with a wrapper delegate class.  Two results to report.  

Firstly, with the latest cli tool I still get the previous exception I mentioned, so maybe this is something more general with using Kotlin.  (btw Kotlin was working fine with your June'19 build until I added a 'by lazy' statement.)

Secondly, I tried the previous cli I had been using from June last year.  Now I get a different exception there.

My class to support div:

```
interface ExtDiv : Element {
    @OpaqueProperty
    fun clientWidth(): Int

    @OpaqueProperty
    fun clientHeight(): Int

    @OpaqueProperty
    fun style(stlye: String)
}
```

My wrapper/delegate class around this so that I can have a 'val' declaration where is is used.

```
class AppWrapper(val app: ExtDiv) {
    init {
        app.style("float:left; width:100%; height:100%;")
    }

    fun clientWidth(): Int {
        return app.clientWidth()
    }

    fun clientHeight(): Int {
        return app.clientHeight()
    }

    fun style(stlye: String) {
        app.style(stlye)
    }

    fun appendChild(canvas: ExtCanvas) {
        app.appendChild(canvas)
    }
}
```

So this allows me to access my target div like so:

`val app = AppWrapper(document.getElementById("app") as ExtDiv)`

But results in the following:

```

INFO: Linked  de.mirkosertic.bytecoder.classlib.MemoryManager
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: java.lang.IllegalStateException: Error relooping cfg for art/AppWrapper.clientWidth INT()
        at de.mirkosertic.bytecoder.backend.wasm.WASMSSAASTCompilerBackend.lambda$null$5(WASMSSAASTCompilerBackend.java:586)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
        at de.mirkosertic.bytecoder.backend.wasm.WASMSSAASTCompilerBackend.lambda$generateCodeFor$6(WASMSSAASTCompilerBackend.java:442)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
        at de.mirkosertic.bytecoder.backend.wasm.WASMSSAASTCompilerBackend.generateCodeFor(WASMSSAASTCompilerBackend.java:377)
        at de.mirkosertic.bytecoder.backend.wasm.WASMSSAASTCompilerBackend.generateCodeFor(WASMSSAASTCompilerBackend.java:43)
        at de.mirkosertic.bytecoder.backend.CompileTarget.compile(CompileTarget.java:127)
        at de.mirkosertic.bytecoder.cli.BytecoderCLI.main(BytecoderCLI.java:111)
        ... 8 more
Caused by: java.lang.IllegalStateException: There seems to be some confusion here, either multiple OpaqueTypes with method named "clientWidth" or mix of Opaque and Non-Opaque virtual invocations in class list [art.AppWrapper, ext.ExtDiv]
        at de.mirkosertic.bytecoder.backend.wasm.WASMSSAASTWriter.invokeVirtualValue(WASMSSAASTWriter.java:989)
        at de.mirkosertic.bytecoder.backend.wasm.WASMSSAASTWriter.toValue(WASMSSAASTWriter.java:665)
        at de.mirkosertic.bytecoder.backend.wasm.WASMSSAASTWriter.generateInitVariableExpression(WASMSSAASTWriter.java:602)
        at de.mirkosertic.bytecoder.backend.wasm.WASMSSAASTWriter.generateExpressions(WASMSSAASTWriter.java:297)
        at de.mirkosertic.bytecoder.backend.wasm.WASMSSAASTWriter.writeExpressionList(WASMSSAASTWriter.java:284)
        at de.mirkosertic.bytecoder.backend.wasm.WASMSSAASTWriter.writeSimpleBlock(WASMSSAASTWriter.java:1505)
        at de.mirkosertic.bytecoder.backend.wasm.WASMSSAASTWriter.writeReloopedInternal(WASMSSAASTWriter.java:1467)
        at de.mirkosertic.bytecoder.backend.wasm.WASMSSAASTWriter.writeRelooped(WASMSSAASTWriter.java:1447)
        at de.mirkosertic.bytecoder.backend.wasm.WASMSSAASTCompilerBackend.lambda$null$5(WASMSSAASTCompilerBackend.java:584)
```

**Comment by WhiteHexagon** [comment]
So I stripped the Kotlin down to the following minimum and June'19 cli runs, but Feb'20 fails

```
class EntryKotlin {
    companion object {
        @JvmStatic
        fun main(args: Array<String>?) {
            EntryKotlin()
        }
    }
}
```

**Comment by WhiteHexagon** [comment]
Additionally, it seem Kotlin Function Types also cause similar exceptions to the first one listed in my original report.

**Comment by mirkosertic** [comment]
I've added a testcase to the current release '2020-03-30'. Lazy init is working. Can you confirm?

**Comment by WhiteHexagon** [comment]
Thanks! but sadly I still can't run the newer CLI builds with Kotlin due to the UTF_8 error mentioned above.  Including your latest build, same error...

https://github.com/mirkosertic/Bytecoder/issues/333#issuecomment-596203543

Kotlin version 1.3.21-release-158 (JRE 1.8.0_161-b12)

**Comment by mirkosertic** [comment]
Can you please update Kotlin to `1.3.71`?

**Comment by WhiteHexagon** [comment]
OK I couldn't do that easily in intelliJ and keep my current setup, dont ask... but I got it building from the command line with 1.3.71 but I get the same exception.

**Comment by WhiteHexagon** [comment]
I also found an option that Kotlin can target jvm 1.6 or 1.8, I tried both, but no difference.

**Comment by mirkosertic** [comment]
Hmm, I still cannot reproduce this issue here. Are you able/allowed to submit your `art-trimmed-all.jar` file?

**Comment by WhiteHexagon** [comment]
It's 35MB since I use shadowJar to package up the .jar prior to CLI call.  I stripped the kotlin down to a couple printlns.  I hope this works:

http://peterbridge.com/art-trimmed-all.jar.zip

**Comment by WhiteHexagon** [comment]
OK good news! I found my shadowJar config is pulling in the the old version of bytecoder.web and core!!  So even though I use the latest bytecoder CLI tool to do the build, maybe this somehow causes a clash with the version within fat Jar?  Not sure, but anyway, when I updated the shadowJar config, the UTF_8 error goes away, Yay!! that has been puzzling me for a while!

**Comment by WhiteHexagon** [comment]
more good news, the by lazy is now working :) thanks!

btw the .wasm file has jumped by 560KB to 720KB , but maybe that is the GC stuff for the new version?  Anyway tomorrow I try the new llvm target.

**Comment by mirkosertic** [comment]
Yeah! Thats the thing I wanted to check. Good you found the problem by yourself!
I don't think you have to include the Bytecoder jars into the shadow jar. You only have to include the Kotlin dependencies. Everything else is pulled into the classpath by the cli.

The increase in file size is due to the "more completeness" of java SDK support. Please try the LLVM target, it should give better results in performance and file size, usually 20-40% smaller than the original wasm compile target. Please note that LLVM compilation takes longer than the wasm backend, so expect an increase in compilation time.

**Comment by WhiteHexagon** [comment]
I tried the suggested LLVM target, but I get an error running the CLI.  I narrowed it down to this:

```
class EntryKotlin {
    private data class DemoTile(var fps: Int)
    private val t1 = DemoTile(3)

    init {
        println("EntryKotlin:init")
        t1.fps++
        println("${t1.fps}")
    }

    companion object {
        @JvmStatic
        fun main(args: Array<String>?) {
            EntryKotlin()
            println("hello world")
        }

    }
}


```

resulting in this:
```
WARNING: Class java.lang.CharacterDataUndefined is used by reflection!
Apr 06, 2020 8:50:18 AM org.slf4j.impl.JCLLoggerAdapter info
INFO: LLVM compiler command is [llc-10, -O2, -filetype=obj, llvm3014691057908261683.ll, -o, llvm3014691057908261683.ll.o]
llc-10: error: llc-10: llvm3014691057908261683.ll:90273:76: error: expected ')' at end of argument list
define internal void @aEntryKotlin$DemoTile_VOIDsetFpsINT(i32 %__tr_,i32 %_<set-?>_) !dbg !5689 {
                                                                           ^

Apr 06, 2020 8:50:18 AM org.slf4j.impl.JCLLoggerAdapter warn
WARNING: llc returned with exit code 1
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)
Caused by: java.lang.RuntimeException: llc reported an error!
        at de.mirkosertic.bytecoder.backend.llvm.LLVMCompilerBackend.generateCodeFor(LLVMCompilerBackend.java:2596)
        at de.mirkosertic.bytecoder.backend.llvm.LLVMCompilerBackend.generateCodeFor(LLVMCompilerBackend.java:77)
        at de.mirkosertic.bytecoder.backend.CompileTarget.compile(CompileTarget.java:210)
        at de.mirkosertic.bytecoder.cli.BytecoderCLI.main(BytecoderCLI.java:129)

```

I hope my LLVM is setup correct, I had to add another symbolic link for the llc-10 which I didnt have.  btw is there a way to show the command line calls that CLI is making?

**Comment by mirkosertic** [comment]
It seems Kotlin generates some strange debug symbol names in this situation. The problem occours in any backend, the generated .wat file from the wasm backend is also corrupt. Only the wasm file is ok as WebAssembly binaries do not rely on naming conventions. I've created a fix and will it release in the next days.
This ticket is related to the by lazy init problem. I think this is solved, so I'd like to close this one.

**Comment by mirkosertic** [comment]
I've released Bytecoder `2020-04-09` which includes the mentioned bug fix.

**Comment by WhiteHexagon** [comment]
I missed the notification about this, but that is great news! I shall get back to testing it then :)
