### ISSUE TITLE
Java to JavaScript Cannot find static method getSystemResource in java/lang/ClassLoader...

### ISSUE THREAD

**Issue by raffazizzi** [mirkosertic/Bytecoder#334]
Hello, I'm trying to transpile some simple Java code for XML validation using [jing](https://github.com/relaxng/jing-trang), but I'm running into the error below.

Here's a repository with the code to reproduce it. https://github.com/raffazizzi/bytecoder-test
I'm using the cli executable: `bytecoder-cli-2019-12-08-executable.jar`.

Error stack:

```
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)
Caused by: java.lang.IllegalStateException: Cannot find static method getSystemResource in java/lang/ClassLoader with signature java.net.URL(java.lang.String)
	at de.mirkosertic.bytecoder.core.BytecodeInstructionINVOKESTATIC.performLinking(BytecodeInstructionINVOKESTATIC.java:35)
	at de.mirkosertic.bytecoder.core.BytecodeLinkedClass.resolveMethodSignatureAndBody(BytecodeLinkedClass.java:410)
	at de.mirkosertic.bytecoder.core.BytecodeLinkedClass.resolveVirtualMethod(BytecodeLinkedClass.java:299)
	at de.mirkosertic.bytecoder.core.BytecodeInstructionINVOKEVIRTUAL.performLinking(BytecodeInstructionINVOKEVIRTUAL.java:54)
	at de.mirkosertic.bytecoder.core.BytecodeLinkedClass.resolveMethodSignatureAndBody(BytecodeLinkedClass.java:410)
	at de.mirkosertic.bytecoder.core.BytecodeLinkedClass.resolveConstructorInvocation(BytecodeLinkedClass.java:330)
	at de.mirkosertic.bytecoder.core.BytecodeInstructionINVOKESPECIAL.performLinking(BytecodeInstructionINVOKESPECIAL.java:36)
	at de.mirkosertic.bytecoder.core.BytecodeLinkedClass.resolveMethodSignatureAndBody(BytecodeLinkedClass.java:410)
	at de.mirkosertic.bytecoder.core.BytecodeLinkedClass.resolveStaticMethod(BytecodeLinkedClass.java:380)
	at de.mirkosertic.bytecoder.core.BytecodeInstructionINVOKESTATIC.performLinking(BytecodeInstructionINVOKESTATIC.java:34)
	at de.mirkosertic.bytecoder.core.BytecodeLinkedClass.resolveMethodSignatureAndBody(BytecodeLinkedClass.java:410)
	at de.mirkosertic.bytecoder.core.BytecodeLinkedClass.resolveConstructorInvocation(BytecodeLinkedClass.java:330)
	at de.mirkosertic.bytecoder.core.BytecodeInstructionINVOKESPECIAL.performLinking(BytecodeInstructionINVOKESPECIAL.java:36)
	at de.mirkosertic.bytecoder.core.BytecodeLinkedClass.resolveMethodSignatureAndBody(BytecodeLinkedClass.java:410)
	at de.mirkosertic.bytecoder.core.BytecodeLinkedClass.resolveConstructorInvocation(BytecodeLinkedClass.java:330)
	at de.mirkosertic.bytecoder.core.BytecodeInstructionINVOKESPECIAL.performLinking(BytecodeInstructionINVOKESPECIAL.java:36)
	at de.mirkosertic.bytecoder.core.BytecodeLinkedClass.resolveMethodSignatureAndBody(BytecodeLinkedClass.java:410)
	at de.mirkosertic.bytecoder.core.BytecodeLinkedClass.resolveConstructorInvocation(BytecodeLinkedClass.java:330)
	at de.mirkosertic.bytecoder.core.BytecodeInstructionINVOKESPECIAL.performLinking(BytecodeInstructionINVOKESPECIAL.java:36)
	at de.mirkosertic.bytecoder.core.BytecodeLinkedClass.resolveMethodSignatureAndBody(BytecodeLinkedClass.java:410)
	at de.mirkosertic.bytecoder.core.BytecodeLinkedClass.resolveStaticMethod(BytecodeLinkedClass.java:380)
	at de.mirkosertic.bytecoder.core.BytecodeInstructionINVOKESTATIC.performLinking(BytecodeInstructionINVOKESTATIC.java:34)
	at de.mirkosertic.bytecoder.core.BytecodeLinkedClass.resolveMethodSignatureAndBody(BytecodeLinkedClass.java:410)
	at de.mirkosertic.bytecoder.core.BytecodeLinkedClass.resolveStaticMethod(BytecodeLinkedClass.java:380)
	at de.mirkosertic.bytecoder.backend.CompileTarget.compile(CompileTarget.java:115)
	at de.mirkosertic.bytecoder.cli.BytecoderCLI.main(BytecoderCLI.java:124)
	... 8 more
```

**Comment by mirkosertic** [comment]
Ressource loading is currently not supported by Bytecoder. Also, transpiling a XML validator won't probably work at all as Bytecoder only has a very limited support of the Java Reflection API, and most of the XML APIs are heavily reflection based.

**Comment by raffazizzi** [comment]
Thank you @mirkosertic . Do you have any suggestions on other possibilities I could explore for using Java libraries (Jing is all I need) in a node.js context without relying on system calls to Java? I'm thinking of exploring using LLVM to get access to emscripten, but I'm running out of ideas.

**Comment by intrigus** [comment]
Graalvm maybe?

**Comment by mirkosertic** [comment]
@raffazizzi i guess you need a js native version then. A quick investigation revealed the following npm package: https://www.npmjs.com/package/salve. Maybe this does the job, but I haven't tried it yet.

**Comment by mirkosertic** [comment]
Closed due to no further feedback.
