### ISSUE TITLE
Jump-start demo crashes

### ISSUE THREAD

**Issue by ebremer** [mirkosertic/Bytecoder#399]
I was trying out your "Jump-start" demo at: https://mirkosertic.github.io/Bytecoder/chapter-1/page-1-a/

and when I executed "java -jar bytecoder-cli-2020-05-04-executable.jar -classpath=. -mainclass=HelloWorld -builddirectory=. -backend=js -minify=false"

it crashed with the following error:
...
May 08, 2020 12:08:02 AM org.slf4j.impl.JCLLoggerAdapter info
INFO: Linked java.util.HashMap$KeyIterator
May 08, 2020 12:08:02 AM org.slf4j.impl.JCLLoggerAdapter info
INFO: Linked java.util.AbstractMap$1$1
May 08, 2020 12:08:02 AM org.slf4j.impl.JCLLoggerAdapter info
INFO: Linked sun.text.normalizer.CodePointMap$RangeIterator
May 08, 2020 12:08:02 AM org.slf4j.impl.JCLLoggerAdapter info
INFO: Linked sun.text.normalizer.CodePointMap$Range
May 08, 2020 12:08:02 AM org.slf4j.impl.JCLLoggerAdapter info
INFO: Linked sun.text.normalizer.NormalizerImpl$UTF16Plus
May 08, 2020 12:08:02 AM org.slf4j.impl.JCLLoggerAdapter info
INFO: Linked java.lang.ArrayIndexOutOfBoundsException
May 08, 2020 12:08:02 AM org.slf4j.impl.JCLLoggerAdapter info
INFO: Linked sun.text.normalizer.CodePointMap$ValueFilter
May 08, 2020 12:08:03 AM org.slf4j.impl.JCLLoggerAdapter info
INFO: Resolving abstract method hierarchy
May 08, 2020 12:08:03 AM org.slf4j.impl.JCLLoggerAdapter info
INFO: Linked java.util.Vector
May 08, 2020 12:08:03 AM org.slf4j.impl.JCLLoggerAdapter info
INFO: Linked java.util.Stack
May 08, 2020 12:08:03 AM org.slf4j.impl.JCLLoggerAdapter info
INFO: Linked de.mirkosertic.bytecoder.classlib.ExceptionManager
May 08, 2020 12:08:03 AM org.slf4j.impl.JCLLoggerAdapter info
INFO: Linked java.util.EmptyStackException
May 08, 2020 12:08:03 AM org.slf4j.impl.JCLLoggerAdapter info
INFO: Compiling java.lang.Object.<init>
May 08, 2020 12:08:03 AM org.slf4j.impl.JCLLoggerAdapter info
INFO: Compiling java.lang.Object.equals
May 08, 2020 12:08:03 AM org.slf4j.impl.JCLLoggerAdapter info
INFO: Compiling java.lang.Object.toString
May 08, 2020 12:08:03 AM org.slf4j.impl.JCLLoggerAdapter info
INFO: Compiling java.lang.Object.hashCode
May 08, 2020 12:08:03 AM org.slf4j.impl.JCLLoggerAdapter info
INFO: Compiling java.lang.Object.clone
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)
Caused by: java.lang.StringIndexOutOfBoundsException: begin 0, end -1, length 10
        at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3319)
        at java.base/java.lang.String.substring(String.java:1874)
        at de.mirkosertic.bytecoder.backend.js.JSMinifier.toClassNameInternal(JSMinifier.java:75)
        at de.mirkosertic.bytecoder.backend.js.JSMinifier.toClassName(JSMinifier.java:64)
        at de.mirkosertic.bytecoder.backend.js.JSSSACompilerBackend.lambda$generateCodeFor$6(JSSSACompilerBackend.java:916)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654)
        at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
        at de.mirkosertic.bytecoder.backend.js.JSSSACompilerBackend.generateCodeFor(JSSSACompilerBackend.java:911)
        at de.mirkosertic.bytecoder.backend.js.JSSSACompilerBackend.generateCodeFor(JSSSACompilerBackend.java:59)
        at de.mirkosertic.bytecoder.backend.CompileTarget.compile(CompileTarget.java:210)
        at de.mirkosertic.bytecoder.cli.BytecoderCLI.main(BytecoderCLI.java:129)
        ... 8 more

**Comment by mirkosertic** [comment]
Thank you for trying Bytecoder.
The example mentioned a package name for the HelloWorld class. Your CLI invocation does not contain a package name, so I guess you leaved it out. Bytecoder currently requires a packagename for all classes, so this might trigger the exception.

**Comment by ebremer** [comment]
That worked.  Thanks! - E
