### ISSUE TITLE
RuntimeError:unreachable error from Vue.js WebAssembly integration test

### ISSUE THREAD

**Issue by jhoyongpark** [mirkosertic/Bytecoder#430]
Multiple clicks of 'Click me to change the message' ends up 'RuntimeError: unreachable'.
This seems to be the common behavior from ClickHandler of button.
I saw the same behavior from my test program.
This is from 2020-07-01 version.

`vue.js:634 [Vue warn]: Error in v-on handler: "RuntimeError: unreachable"
(found in <Root>)
vue.js:1897 RuntimeError: unreachable
    at https://mirkosertic.github.io/Bytecoder/vue_wasm.wasm:wasm-function[1665]:0x47ea6
    at dmbavVueEventListener_VOIDhandledmbavVueInstancedmbawEvent (https://mirkosertic.github.io/Bytecoder/vue_wasm.wasm:wasm-function[2907]:0x8a877)
    at Vue.<anonymous> (https://mirkosertic.github.io/Bytecoder/vue_wasm.js:377:263)
    at Vue.config.methods.<computed> (https://mirkosertic.github.io/Bytecoder/vuewasm.html:91:42)
    at invokeWithErrorHandling (https://cdn.jsdelivr.net/npm/vue/dist/vue.js:1863:28)
    at HTMLButtonElement.invoker (https://cdn.jsdelivr.net/npm/vue/dist/vue.js:2188:16)
    at HTMLButtonElement.original._wrapper (https://cdn.jsdelivr.net/npm/vue/dist/vue.js:7547:27)`

**Comment by mirkosertic** [comment]
Fixed with Release 2020-07-29. It was a subtle bug in the garbage collector logic.
