### ISSUE TITLE
fail to build mvn install 

### ISSUE THREAD

**Issue by metrospiegel** [mirkosertic/Bytecoder#6]
Results :

Tests in error: 
  testValueOfNegativeString JS Backend jsssacompiler(de.mirkosertic.bytecoder.classlib.java.lang.TByteTest): Error linking class de.mirkosertic.bytecoder.classlib.java.lang.TFloat
  testParseByte JS Backend jsssacompiler(de.mirkosertic.bytecoder.classlib.java.lang.TByteTest): Error linking class de.mirkosertic.bytecoder.classlib.java.lang.TFloat
  testValueOfString JS Backend jsssacompiler(de.mirkosertic.bytecoder.classlib.java.lang.TByteTest): Error linking class de.mirkosertic.bytecoder.classlib.java.lang.TFloat
  testValueOfNegativeString JS Backend jsssacompiler(de.mirkosertic.bytecoder.classlib.java.lang.TDoubleTest): Error linking class de.mirkosertic.bytecoder.classlib.java.lang.TLong
  testValueOfString2 JS Backend jsssacompiler(de.mirkosertic.bytecoder.classlib.java.lang.TDoubleTest): Error linking class de.mirkosertic.bytecoder.classlib.java.lang.TLong
  testValueOfString JS Backend jsssacompiler(de.mirkosertic.bytecoder.classlib.java.lang.TDoubleTest): Error linking class de.mirkosertic.bytecoder.classlib.java.lang.TLong
  testParseDouble JS Backend jsssacompiler(de.mirkosertic.bytecoder.classlib.java.lang.TDoubleTest): Error linking class de.mirkosertic.bytecoder.classlib.java.lang.TLong
  testValueOfString1 JS Backend jsssacompiler(de.mirkosertic.bytecoder.classlib.java.lang.TDoubleTest): Error linking class de.mirkosertic.bytecoder.classlib.java.lang.TLong
  testValueOfNegativeString JS Backend jsssacompiler(de.mirkosertic.bytecoder.classlib.java.lang.TFloatTest): Error linking class de.mirkosertic.bytecoder.classlib.java.lang.TLong
  testValueOfString2 JS Backend jsssacompiler(de.mirkosertic.bytecoder.classlib.java.lang.TFloatTest): Error linking class de.mirkosertic.bytecoder.classlib.java.lang.TLong
  testParseFloat JS Backend jsssacompiler(de.mirkosertic.bytecoder.classlib.java.lang.TFloatTest): Error linking class de.mirkosertic.bytecoder.classlib.java.lang.TLong
  testValueOfString JS Backend jsssacompiler(de.mirkosertic.bytecoder.classlib.java.lang.TFloatTest): Error linking class de.mirkosertic.bytecoder.classlib.java.lang.TLong
  testValueOfString1 JS Backend jsssacompiler(de.mirkosertic.bytecoder.classlib.java.lang.TFloatTest): Error linking class de.mirkosertic.bytecoder.classlib.java.lang.TLong
  testValueOfNegativeString JS Backend jsssacompiler(de.mirkosertic.bytecoder.classlib.java.lang.TIntegerTest): Error linking class de.mirkosertic.bytecoder.classlib.java.lang.TFloat
  testValueOfString JS Backend jsssacompiler(de.mirkosertic.bytecoder.classlib.java.lang.TIntegerTest): Error linking class de.mirkosertic.bytecoder.classlib.java.lang.TFloat
  testParseInt JS Backend jsssacompiler(de.mirkosertic.bytecoder.classlib.java.lang.TIntegerTest): Error linking class de.mirkosertic.bytecoder.classlib.java.lang.TFloat
  testValueOfNegativeString JS Backend jsssacompiler(de.mirkosertic.bytecoder.classlib.java.lang.TLongTest): Error linking class de.mirkosertic.bytecoder.classlib.java.lang.TFloat
  testValueOfString JS Backend jsssacompiler(de.mirkosertic.bytecoder.classlib.java.lang.TLongTest): Error linking class de.mirkosertic.bytecoder.classlib.java.lang.TFloat
  testParseLong JS Backend jsssacompiler(de.mirkosertic.bytecoder.classlib.java.lang.TLongTest): Error linking class de.mirkosertic.bytecoder.classlib.java.lang.TFloat
  testValueOfNegativeString JS Backend jsssacompiler(de.mirkosertic.bytecoder.classlib.java.lang.TShortTest): Error linking class de.mirkosertic.bytecoder.classlib.java.lang.TFloat
  testValueOfString JS Backend jsssacompiler(de.mirkosertic.bytecoder.classlib.java.lang.TShortTest): Error linking class de.mirkosertic.bytecoder.classlib.java.lang.TFloat
  testParseShort JS Backend jsssacompiler(de.mirkosertic.bytecoder.classlib.java.lang.TShortTest): Error linking class de.mirkosertic.bytecoder.classlib.java.lang.TFloat
  testSimpleExceptionFlow JS Backend jsssacompiler(de.mirkosertic.bytecoder.core.ExceptionHandlerTest): {stack=FLOATflowTest(..)
  testRethrow JS Backend jsssacompiler(de.mirkosertic.bytecoder.core.ExceptionHandlerTest): {stack=VOIDthrowSomething(..)
  testEquals JS Backend jsssacompiler(de.mirkosertic.bytecoder.core.StringTest): {stack=VOIDtestEquals(..)
  testConcatenation JS Backend jsssacompiler(de.mirkosertic.bytecoder.core.StringTest): {stack=VOIDtestConcatenation(..)

Tests run: 434, Failures: 0, Errors: 26, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Bytecoder Parent POM ............................... SUCCESS [  0.733 s]
[INFO] Bytecoder Core ..................................... FAILURE [ 26.521 s]
[INFO] Bytecoder Maven Plugin ............................. SKIPPED
[INFO] Bytecoder Integrationtest .......................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE

-------------------------------------------------------------------------------
Test set: de.mirkosertic.bytecoder.classlib.java.lang.TByteTest
-------------------------------------------------------------------------------
Tests run: 26, Failures: 0, Errors: 3, Skipped: 0, Time elapsed: 0.535 sec <<< FAILURE!
testValueOfNegativeString JS Backend jsssacompiler(de.mirkosertic.bytecoder.classlib.java.lang.TByteTest)  Time elapsed: 0.002 sec  <<< ERROR!
java.lang.RuntimeException: Error linking class de.mirkosertic.bytecoder.classlib.java.lang.TFloat
	at de.mirkosertic.bytecoder.core.BytecodeLinkerContext.linkClass(BytecodeLinkerContext.java:114)
	at de.mirkosertic.bytecoder.core.BytecodeInstructionINVOKESTATIC.performLinking(BytecodeInstructionINVOKESTATIC.java:33)
	at de.mirkosertic.bytecoder.core.BytecodeLinkedClass.linkMethodInternal(BytecodeLinkedClass.java:364)
	at de.mirkosertic.bytecoder.core.BytecodeLinkedClass.linkStaticMethod(BytecodeLinkedClass.java:326)
	at de.mirkosertic.bytecoder.core.BytecodeInstructionINVOKESTATIC.performLinking(BytecodeInstructionINVOKESTATIC.java:33)
	at de.mirkosertic.bytecoder.core.BytecodeLinkedClass.linkMethodInternal(BytecodeLinkedClass.java:364)
	at de.mirkosertic.bytecoder.core.BytecodeLinkedClass.linkStaticMethod(BytecodeLinkedClass.java:326)
	at de.mirkosertic.bytecoder.core.BytecodeInstructionINVOKESTATIC.performLinking(BytecodeInstructionINVOKESTATIC.java:33)
	at de.mirkosertic.bytecoder.core.BytecodeLinkedClass.linkMethodInternal(BytecodeLinkedClass.java:364)
	at de.mirkosertic.bytecoder.core.BytecodeLinkedClass.linkStaticMethod(BytecodeLinkedClass.java:326)
	at de.mirkosertic.bytecoder.backend.CompileTarget.compileToJS(CompileTarget.java:82)
	at de.mirkosertic.bytecoder.unittest.BytecoderUnitTestRunner.testJSBackendFrameworkMethod(BytecoderUnitTestRunner.java:127)
	at de.mirkosertic.bytecoder.unittest.BytecoderUnitTestRunner.runChild(BytecoderUnitTestRunner.java:197)
	at de.mirkosertic.bytecoder.unittest.BytecoderUnitTestRunner.runChild(BytecoderUnitTestRunner.java:1)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Caused by: java.lang.IllegalArgumentException: Error while linking virtual method name charValue for de.mirkosertic.bytecoder.classlib.java.lang.TFloat
	at de.mirkosertic.bytecoder.core.BytecodeLinkedClass.linkVirtualMethod(BytecodeLinkedClass.java:285)
	at de.mirkosertic.bytecoder.core.BytecodeLinkerContext.lambda$linkClass$1(BytecodeLinkerContext.java:106)
	at java.base/java.util.HashMap$EntrySet.forEach(HashMap.java:1044)
	at de.mirkosertic.bytecoder.core.BytecodeLinkedClass.forEachVirtualMethod(BytecodeLinkedClass.java:380)
	at de.mirkosertic.bytecoder.core.BytecodeLinkerContext.linkClass(BytecodeLinkerContext.java:103)
	... 31 more
Caused by: java.lang.NullPointerException
	at de.mirkosertic.bytecoder.core.BytecodeInstructionINVOKEDYNAMIC.performLinking(BytecodeInstructionINVOKEDYNAMIC.java:59)
	at de.mirkosertic.bytecoder.core.BytecodeLinkedClass.linkMethodInternal(BytecodeLinkedClass.java:364)
	at de.mirkosertic.bytecoder.core.BytecodeLinkedClass.linkVirtualMethod(BytecodeLinkedClass.java:252)
	... 35 more

testParseByte JS Backend jsssacompiler(de.mirkosertic.bytecoder.classlib.java.lang.TByteTest)  Time elapsed: 0.007 sec  <<< ERROR!
java.lang.RuntimeException: Error linking class de.mirkosertic.bytecoder.classlib.java.lang.TFloat
	at de.mirkosertic.bytecoder.core.BytecodeLinkerContext.linkClass(BytecodeLinkerContext.java:114)
	at de.mirkosertic.bytecoder.core.BytecodeInstructionINVOKESTATIC.performLinking(BytecodeInstructionINVOKESTATIC.java:33)
	at de.mirkosertic.bytecoder.core.BytecodeLinkedClass.linkMethodInternal(BytecodeLinkedClass.java:364)
	at de.mirkosertic.bytecoder.core.BytecodeLinkedClass.linkStaticMethod(BytecodeLinkedClass.java:326)
	at de.mirkosertic.bytecoder.core.BytecodeInstructionINVOKESTATIC.performLinking(BytecodeInstructionINVOKESTATIC.java:33)
	at de.mirkosertic.bytecoder.core.BytecodeLinkedClass.linkMethodInternal(BytecodeLinkedClass.java:364)
	at de.mirkosertic.bytecoder.core.BytecodeLinkedClass.linkStaticMethod(BytecodeLinkedClass.java:326)
	at de.mirkosertic.bytecoder.core.BytecodeInstructionINVOKESTATIC.performLinking(BytecodeInstructionINVOKESTATIC.java:33)
	at de.mirkosertic.bytecoder.core.BytecodeLinkedClass.linkMethodInternal(BytecodeLinkedClass.java:364)
	at de.mirkosertic.bytecoder.core.BytecodeLinkedClass.linkStaticMethod(BytecodeLinkedClass.java:326)
	at de.mirkosertic.bytecoder.backend.CompileTarget.compileToJS(CompileTarget.java:82)
	at de.mirkosertic.bytecoder.unittest.BytecoderUnitTestRunner.testJSBackendFrameworkMethod(BytecoderUnitTestRunner.java:127)
	at de.mirkosertic.bytecoder.unittest.BytecoderUnitTestRunner.runChild(BytecoderUnitTestRunner.java:197)
	at de.mirkosertic.bytecoder.unittest.BytecoderUnitTestRunner.runChild(BytecoderUnitTestRunner.java:1)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Caused by: java.lang.IllegalArgumentException: Error while linking virtual method name charValue for de.mirkosertic.bytecoder.classlib.java.lang.TFloat
	at de.mirkosertic.bytecoder.core.BytecodeLinkedClass.linkVirtualMethod(BytecodeLinkedClass.java:285)
	at de.mirkosertic.bytecoder.core.BytecodeLinkerContext.lambda$linkClass$1(BytecodeLinkerContext.java:106)
	at java.base/java.util.HashMap$EntrySet.forEach(HashMap.java:1044)
	at de.mirkosertic.bytecoder.core.BytecodeLinkedClass.forEachVirtualMethod(BytecodeLinkedClass.java:380)
	at de.mirkosertic.bytecoder.core.BytecodeLinkerContext.linkClass(BytecodeLinkerContext.java:103)
	... 31 more
Caused by: java.lang.NullPointerException
	at de.mirkosertic.bytecoder.core.BytecodeInstructionINVOKEDYNAMIC.performLinking(BytecodeInstructionINVOKEDYNAMIC.java:59)
	at de.mirkosertic.bytecoder.core.BytecodeLinkedClass.linkMethodInternal(BytecodeLinkedClass.java:364)
	at de.mirkosertic.bytecoder.core.BytecodeLinkedClass.linkVirtualMethod(BytecodeLinkedClass.java:252)
	... 35 more

testValueOfString JS Backend jsssacompiler(de.mirkosertic.bytecoder.classlib.java.lang.TByteTest)  Time elapsed: 0.006 sec  <<< ERROR!
java.lang.RuntimeException: Error linking class de.mirkosertic.bytecoder.classlib.java.lang.TFloat
	at de.mirkosertic.bytecoder.core.BytecodeLinkerContext.linkClass(BytecodeLinkerContext.java:114)
	at de.mirkosertic.bytecoder.core.BytecodeInstructionINVOKESTATIC.performLinking(BytecodeInstructionINVOKESTATIC.java:33)
	at de.mirkosertic.bytecoder.core.BytecodeLinkedClass.linkMethodInternal(BytecodeLinkedClass.java:364)
	at de.mirkosertic.bytecoder.core.BytecodeLinkedClass.linkStaticMethod(BytecodeLinkedClass.java:326)
	at de.mirkosertic.bytecoder.core.BytecodeInstructionINVOKESTATIC.performLinking(BytecodeInstructionINVOKESTATIC.java:33)
	at de.mirkosertic.bytecoder.core.BytecodeLinkedClass.linkMethodInternal(BytecodeLinkedClass.java:364)
	at de.mirkosertic.bytecoder.core.BytecodeLinkedClass.linkStaticMethod(BytecodeLinkedClass.java:326)
	at de.mirkosertic.bytecoder.core.BytecodeInstructionINVOKESTATIC.performLinking(BytecodeInstructionINVOKESTATIC.java:33)
	at de.mirkosertic.bytecoder.core.BytecodeLinkedClass.linkMethodInternal(BytecodeLinkedClass.java:364)
	at de.mirkosertic.bytecoder.core.BytecodeLinkedClass.linkStaticMethod(BytecodeLinkedClass.java:326)
	at de.mirkosertic.bytecoder.backend.CompileTarget.compileToJS(CompileTarget.java:82)
	at de.mirkosertic.bytecoder.unittest.BytecoderUnitTestRunner.testJSBackendFrameworkMethod(BytecoderUnitTestRunner.java:127)
	at de.mirkosertic.bytecoder.unittest.BytecoderUnitTestRunner.runChild(BytecoderUnitTestRunner.java:197)
	at de.mirkosertic.bytecoder.unittest.BytecoderUnitTestRunner.runChild(BytecoderUnitTestRunner.java:1)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Caused by: java.lang.IllegalArgumentException: Error while linking virtual method name charValue for de.mirkosertic.bytecoder.classlib.java.lang.TFloat
	at de.mirkosertic.bytecoder.core.BytecodeLinkedClass.linkVirtualMethod(BytecodeLinkedClass.java:285)
	at de.mirkosertic.bytecoder.core.BytecodeLinkerContext.lambda$linkClass$1(BytecodeLinkerContext.java:106)
	at java.base/java.util.HashMap$EntrySet.forEach(HashMap.java:1044)
	at de.mirkosertic.bytecoder.core.BytecodeLinkedClass.forEachVirtualMethod(BytecodeLinkedClass.java:380)
	at de.mirkosertic.bytecoder.core.BytecodeLinkerContext.linkClass(BytecodeLinkerContext.java:103)
	... 31 more
Caused by: java.lang.NullPointerException
	at de.mirkosertic.bytecoder.core.BytecodeInstructionINVOKEDYNAMIC.performLinking(BytecodeInstructionINVOKEDYNAMIC.java:59)
	at de.mirkosertic.bytecoder.core.BytecodeLinkedClass.linkMethodInternal(BytecodeLinkedClass.java:364)
	at de.mirkosertic.bytecoder.core.BytecodeLinkedClass.linkVirtualMethod(BytecodeLinkedClass.java:252)
	... 35 more

**Comment by mirkosertic** [comment]
Bytecoder is currently under heavy development, and there are some bugs causing the build to fail.
