### ISSUE TITLE
How to compile a project with multiple classpaths?

### ISSUE THREAD

**Issue by EchoStone1101** [mirkosertic/Bytecoder#913]
Sorry if I missed anything obvious, but I am trying to compile a Main.class into WASM, which takes multiple classpaths as dependencies. The version of bytecoder is ` bytecoder-cli-2023-04-24-executable.jar`.

The closest I got to working is with something like:
```bash
java -jar bytecoder-cli-2023-04-24-executable.jar compile wasm -classpath=CLASSPATH-A -builddirectory=../build -mainclass=my.target.Main
```

However, `my.target.Main` actually needs `-cp CLASSPATH-A:CLASSPATH-B:CLASSPATH-C...` to compile and run, so Bytecoder CLI will just give me ClassNotFoundException:
```log
5月 22, 2023 3:18:22 下午 de.mirkosertic.bytecoder.core.Slf4JLogger info
信息: Compiling main class net.handle.server.Main to directory ../build
Current Analysis Stack is : 
Parsing method body of Lnet/handle/server/Main;.main
 Parsing method body of Lnet/cnri/util/StreamTable;.readFromFile
   Visiting #2 NEW Stack size is 0 Source line 147
   Local 0 of type Lnet/cnri/util/StreamTable;
   Local 1 of type Ljava/io/File;
de.mirkosertic.bytecoder.core.ir.AnalysisException: java.lang.RuntimeException: java.lang.ClassNotFoundException: net/cnri/io/AtomicFile.class
	at de.mirkosertic.bytecoder.core.ir.ResolvedMethod.parseBody(ResolvedMethod.java:50)
	at de.mirkosertic.bytecoder.core.ir.ResolvedClass.resolveMethodInternal(ResolvedClass.java:134)
	at de.mirkosertic.bytecoder.core.ir.ResolvedClass.resolveMethod(ResolvedClass.java:110)
	at de.mirkosertic.bytecoder.core.parser.GraphParser.parse_INVOKEVIRTUAL(GraphParser.java:685)
	at de.mirkosertic.bytecoder.core.parser.GraphParser.parseMethodInsNode(GraphParser.java:856)
	at de.mirkosertic.bytecoder.core.parser.GraphParser.parse(GraphParser.java:2607)
	at de.mirkosertic.bytecoder.core.parser.GraphParser.parse(GraphParser.java:405)
	at de.mirkosertic.bytecoder.core.parser.GraphParser.<init>(GraphParser.java:150)
	at de.mirkosertic.bytecoder.core.ir.ResolvedMethod.parseBody(ResolvedMethod.java:45)
	at de.mirkosertic.bytecoder.core.ir.ResolvedClass.resolveMethodInternal(ResolvedClass.java:134)
	at de.mirkosertic.bytecoder.core.ir.ResolvedClass.resolveMethod(ResolvedClass.java:110)
	at de.mirkosertic.bytecoder.core.parser.CompileUnit.resolveMainMethod(CompileUnit.java:213)
	at de.mirkosertic.bytecoder.cli.CompileWasmCommand.call(CompileWasmCommand.java:87)
	at de.mirkosertic.bytecoder.cli.CompileWasmCommand.call(CompileWasmCommand.java:41)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at de.mirkosertic.bytecoder.cli.BytecoderCLI.main(BytecoderCLI.java:24)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65)
Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: net/cnri/io/AtomicFile.class
	at de.mirkosertic.bytecoder.core.parser.CompileUnit.resolveClass(CompileUnit.java:120)
	at de.mirkosertic.bytecoder.core.parser.GraphParser.parse_NEW(GraphParser.java:1964)
	at de.mirkosertic.bytecoder.core.parser.GraphParser.parseTypeInsnNode(GraphParser.java:2085)
	at de.mirkosertic.bytecoder.core.parser.GraphParser.parse(GraphParser.java:2619)
	at de.mirkosertic.bytecoder.core.parser.GraphParser.parse(GraphParser.java:405)
	at de.mirkosertic.bytecoder.core.parser.GraphParser.<init>(GraphParser.java:150)
	at de.mirkosertic.bytecoder.core.ir.ResolvedMethod.parseBody(ResolvedMethod.java:45)
	... 30 more
Caused by: java.lang.ClassNotFoundException: net/cnri/io/AtomicFile.class
	at de.mirkosertic.bytecoder.core.loader.BytecoderLoader.internalLoad(BytecoderLoader.java:97)
	at de.mirkosertic.bytecoder.core.loader.BytecoderLoader.loadClassFor(BytecoderLoader.java:61)
	at de.mirkosertic.bytecoder.core.parser.CompileUnit.resolveClass(CompileUnit.java:116)
	... 36 more
```

Obviously I tried to provide the full colon-separated classpath in `-classpath`, but apparently (and to my understanding) this option is for the target class only, and it doesn't work.
I see there are `-additionalResources` and `-additionalClassesToLink`, but I'm not sure if they are relevant.

So my question: is it possible to compile a class with multiple classpaths, and how?

**Comment by nbrugger-tgm** [comment]
I created a pr for this :)  #920

**Comment by nbrugger-tgm** [comment]
Is it released? If yes close this issue

**Comment by mirkosertic** [comment]
Release with https://github.com/mirkosertic/Bytecoder/releases/tag/2023-06-15
